import Frank from '../images/users/1_Frank.jpg';
import Ronald from '../images/users/2_Ronald.jpg';
import Crystal from '../images/users/3_Crystal.jpg';

import showshank from '../images/films/1_showshank.jpg';
import godfather from '../images/films/2_godfather.jpg';
import twelveangrymen from '../images/films/3_12angrymen.jpg';
import darknight from '../images/films/4_darknight.jpg';
import pulpfiction from '../images/films/5_pulpfiction.jpg';
import ganman from '../images/films/6_ganman.jpg';
import list from '../images/films/7_list.jpg';
import fightclub from '../images/films/8_fightclub.jpg';
import inception from '../images/films/9_inception.jpg';
import loadoftherings from '../images/films/10_loadoftherings.jpg';

export const sampleData = [
  {
    id: '1',
    uid: 'frank',
    displayName: 'Frank',
    photoURL: Frank,
    createdAt: '2021-05-19',
    films: [
      {
        id: '11111',
        title: 'ショーシャンクの空に',
        photoURL: showshank,
        release: '1994',
        director: 'フランク・ダラボン',
        description: '映画の説明文',
      },
      {
        id: '22222',
        photoURL: godfather,
        title: 'ゴッド・ファーザー',
        release: '1972',
        director: 'フランシス・フォード・コッポラ',
        description: '映画の説明文',
      },
      {
        id: '33333',
        photoURL: twelveangrymen,
        title: '十二の怒れる男',
        release: '1957',
        director: 'シドニー・ルメット',
        description: '映画の説明文',
      },
      {
        id: '44444',
        photoURL: darknight,
        title: 'ダークナイト',
        release: '2008',
        director: 'クリストファー・ノーラン',
        description: '映画の説明文',
      },
      {
        id: '55555',
        photoURL: pulpfiction,
        title: 'パルプ・フィクション',
        release: '1994',
        director: 'クエンティン・タランティーノ',
        description: '映画の説明文',
      },
      {
        id: '66666',
        photoURL: ganman,
        title: '続・夕陽のガンマン',
        release: '1996',
        director: 'セルジオ・レオーネ',
        description: '映画の説明文',
      },
      {
        id: '77777',
        photoURL: list,
        title: 'シンドラーのリスト',
        release: '1994',
        director: 'スティーヴン・スピルバーグ',
        description: '映画の説明文',
      },
      {
        id: '88888',
        photoURL: fightclub,
        title: 'ファイトクラブ',
        release: '1999',
        director: 'フランデヴィッド・フィンチャーク・ダラボン',
        description: '映画の説明文',
      },
      {
        id: '99999',
        photoURL: inception,
        title: 'インセプション',
        release: '2010',
        director: 'クリストファー・ノーラン',
        description: '映画の説明文',
      },
      {
        id: '10101',
        photoURL: loadoftherings,
        title: 'ロード・オブ・ザ・リング',
        release: '2001',
        director: 'ピーター・ジャクソン',
        description: '映画の説明文',
      },
    ],
  },
  {
    id: '2',
    uid: 'ronald',
    displayName: 'Ronald',
    photoURL: Ronald,
    createdAt: '2021-05-19',
    films: [
      {
        id: '11111',
        title: 'ショーシャンクの空に',
        photoURL: showshank,
        release: '1994',
        director: 'フランク・ダラボン',
        description: '映画の説明文',
      },
      {
        id: '22222',
        photoURL: godfather,
        title: 'ゴッド・ファーザー',
        release: '1972',
        director: 'フランシス・フォード・コッポラ',
        description: '映画の説明文',
      },
      {
        id: '33333',
        photoURL: twelveangrymen,
        title: '十二の怒れる男',
        release: '1957',
        director: 'シドニー・ルメット',
        description: '映画の説明文',
      },
      {
        id: '44444',
        photoURL: darknight,
        title: 'ダークナイト',
        release: '2008',
        director: 'クリストファー・ノーラン',
        description: '映画の説明文',
      },
      {
        id: '55555',
        photoURL: pulpfiction,
        title: 'パルプ・フィクション',
        release: '1994',
        director: 'クエンティン・タランティーノ',
        description: '映画の説明文',
      },
      {
        id: '66666',
        photoURL: ganman,
        title: '続・夕陽のガンマン',
        release: '1996',
        director: 'セルジオ・レオーネ',
        description: '映画の説明文',
      },
      {
        id: '77777',
        photoURL: list,
        title: 'シンドラーのリスト',
        release: '1994',
        director: 'スティーヴン・スピルバーグ',
        description: '映画の説明文',
      },
      {
        id: '88888',
        photoURL: fightclub,
        title: 'ファイトクラブ',
        release: '1999',
        director: 'フランデヴィッド・フィンチャーク・ダラボン',
        description: '映画の説明文',
      },
      {
        id: '99999',
        photoURL: inception,
        title: 'インセプション',
        release: '2010',
        director: 'クリストファー・ノーラン',
        description: '映画の説明文',
      },
      {
        id: '10101',
        photoURL: loadoftherings,
        title: 'ロード・オブ・ザ・リング',
        release: '2001',
        director: 'ピーター・ジャクソン',
        description: '映画の説明文',
      },
    ],
  },
  {
    id: '3',
    uid: 'crystal',
    displayName: 'Crystal',
    photoURL: Crystal,
    createdAt: '2021-05-19',
    films: [
      {
        id: '11111',
        title: 'ショーシャンクの空に',
        photoURL: showshank,
        release: '1994',
        director: 'フランク・ダラボン',
        description: '映画の説明文',
      },
      {
        id: '22222',
        photoURL: godfather,
        title: 'ゴッド・ファーザー',
        release: '1972',
        director: 'フランシス・フォード・コッポラ',
        description: '映画の説明文',
      },
      {
        id: '33333',
        photoURL: twelveangrymen,
        title: '十二の怒れる男',
        release: '1957',
        director: 'シドニー・ルメット',
        description: '映画の説明文',
      },
      {
        id: '44444',
        photoURL: darknight,
        title: 'ダークナイト',
        release: '2008',
        director: 'クリストファー・ノーラン',
        description: '映画の説明文',
      },
      {
        id: '55555',
        photoURL: pulpfiction,
        title: 'パルプ・フィクション',
        release: '1994',
        director: 'クエンティン・タランティーノ',
        description: '映画の説明文',
      },
      {
        id: '66666',
        photoURL: ganman,
        title: '続・夕陽のガンマン',
        release: '1996',
        director: 'セルジオ・レオーネ',
        description: '映画の説明文',
      },
      {
        id: '77777',
        photoURL: list,
        title: 'シンドラーのリスト',
        release: '1994',
        director: 'スティーヴン・スピルバーグ',
        description: '映画の説明文',
      },
      {
        id: '88888',
        photoURL: fightclub,
        title: 'ファイトクラブ',
        release: '1999',
        director: 'フランデヴィッド・フィンチャーク・ダラボン',
        description: '映画の説明文',
      },
      {
        id: '99999',
        photoURL: inception,
        title: 'インセプション',
        release: '2010',
        director: 'クリストファー・ノーラン',
        description: '映画の説明文',
      },
      {
        id: '10101',
        photoURL: loadoftherings,
        title: 'ロード・オブ・ザ・リング',
        release: '2001',
        director: 'ピーター・ジャクソン',
        description: '映画の説明文',
      },
    ],
  },
];

export const popularFilms = [
  {
    id: '11111',
    title: 'ショーシャンクの空に',
    photoURL: showshank,
    release: '1994',
    director: 'フランク・ダラボン',
    description: '映画の説明文',
  },
  {
    id: '22222',
    photoURL: godfather,
    title: 'ゴッド・ファーザー',
    release: '1972',
    director: 'フランシス・フォード・コッポラ',
    description: '映画の説明文',
  },
  {
    id: '33333',
    photoURL: twelveangrymen,
    title: '十二の怒れる男',
    release: '1957',
    director: 'シドニー・ルメット',
    description: '映画の説明文',
  },
  {
    id: '44444',
    photoURL: darknight,
    title: 'ダークナイト',
    release: '2008',
    director: 'クリストファー・ノーラン',
    description: '映画の説明文',
  },
  {
    id: '55555',
    photoURL: pulpfiction,
    title: 'パルプ・フィクション',
    release: '1994',
    director: 'クエンティン・タランティーノ',
    description: '映画の説明文',
  },
  {
    id: '66666',
    photoURL: ganman,
    title: '続・夕陽のガンマン',
    release: '1996',
    director: 'セルジオ・レオーネ',
    description: '映画の説明文',
  },
  {
    id: '77777',
    photoURL: list,
    title: 'シンドラーのリスト',
    release: '1994',
    director: 'スティーヴン・スピルバーグ',
    description: '映画の説明文',
  },
  {
    id: '88888',
    photoURL: fightclub,
    title: 'ファイトクラブ',
    release: '1999',
    director: 'フランデヴィッド・フィンチャーク・ダラボン',
    description: '映画の説明文',
  },
  {
    id: '99999',
    photoURL: inception,
    title: 'インセプション',
    release: '2010',
    director: 'クリストファー・ノーラン',
    description: '映画の説明文',
  },
  {
    id: '10101',
    photoURL: loadoftherings,
    title: 'ロード・オブ・ザ・リング',
    release: '2001',
    director: 'ピーター・ジャクソン',
    description: '映画の説明文',
  },
];
